### ISSUE TITLE
make error:CMakeFiles/path_planning.dir/build.make:62: recipe for target 'CMakeFiles/path_planning.dir/src/main.cpp.o' failed

### ISSUE THREAD

**Issue by yunxiaoshan** [mithi/highway-path-planning#1]
As the title, what is the possible reason for that?

**Comment by mithi** [comment]
What OS are you running this?
Have you installed all dependencies correctly without errors on your OS? See dependencies section of https://github.com/udacity/CarND-Path-Planning-Project/blob/master/README.md

**Comment by yunxiaoshan** [comment]
-now I manually install all the dependencies, and re-organize the code in QT. now, it shows that 
`/home/usi/qt_project/high_way_path_planning_v1/src/main.cpp:254: error: no matching function for call to ‘uWS::Hub::onMessage(main()::<lambda(uWS::WebSocket<true>, char*, size_t, uWS::OpCode)>)’
   });
    ^`
and also the .onconnection has the same error.
So, what is the possible reason for that?

**Comment by yunxiaoshan** [comment]
I found the problem, now it could build successfully. It should be caused by the update of the uWebSocket, I just change the ` h.onMessage([&pathConverter,&just_starting](uWS::WebSocket<uWS::SERVER> ws, char *data, size_t length, uWS::OpCode opCode)` to 
` h.onMessage([&pathConverter,&just_starting](uWS::WebSocket<uWS::SERVER>* ws, char *data, size_t length, uWS::OpCode opCode)`. Now `uWS::WebSocket<uWS::SERVER>` only support pointer definition. And also other problems.

**Comment by mithi** [comment]
@yunxiaoshan thanks for sharing the solution! you might also be interested in  running this https://github.com/mithi/bosch-challenge

**Comment by yunxiaoshan** [comment]
H
Hi,
It seems the term 3 simulator does not match the File in Bosch,  any tips
for that?
Best
Shan

**Comment by mithi** [comment]
@yunxiaoshan 

Here's the Bosch simulator: https://github.com/udacity/Bosch-Challenge/releases
